version: "3"

services:
  pulsar:
    image: apachepulsar/pulsar:2.8.0
    container_name: pulsar
    restart: always
    ports:
      - 6650:6650
      - 8080:8080
    command: bin/pulsar standalone
